<a href="https://colab.research.google.com/github/fab-rodrigs/machine-learning/blob/main/machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



> **Aprendizado de máquina**

Detecção qual animal é, com base nas características dele.

In [1]:
# pelo longo?
# perna curta?
# late?

porco1 = [0, 1, 0] # não tem pelo longo, tem perna curta, não late
porco2 = [0, 1, 1] # não tem pelo longo, tem perna curta, late
porco3 = [1, 1, 0] # tem pelo longo, tem perna curta, não late

cachorro1 = [0, 1, 1] # não tem pelo longo, tem perna curta, late
cachorro2 = [1, 0, 1] # tem pelo longo, não tem perna curta, late
cachorro3 = [1, 1, 1] # tem pelo longo, tem perna curta, late

treino_x = [porco1, porco2, porco3, cachorro1, cachorro2, cachorro3] # dados (animais)
classificacoes_y = [1, 1, 1, 0, 0, 0] # 0 = cachorro, 1 = porco

Treino de um "cérebro" vazio

In [2]:
from sklearn.svm import LinearSVC

modelo = LinearSVC()
modelo.fit(treino_x, classificacoes_y)

LinearSVC()

Teste de um animal "misterioso". Resultado = 0 (cachorro), 1 (porco)

In [3]:
animal_misterioso = [1, 1, 1]
modelo.predict([animal_misterioso])

array([0])

In [4]:
misterio1 = [1, 1, 1]
misterio2 = [1, 1, 0]
misterio3 = [0, 1, 1]

teste_x = [misterio1, misterio2, misterio3]
teste_y = [0, 1, 1] # sei que o primeiro é um cachorro, e os outros dois são porcos

previsoes = modelo.predict(teste_x)
previsoes

array([0, 1, 0])

In [5]:
from sklearn.metrics import accuracy_score

accuracy_score(teste_y, previsoes) # taxa de acerto da previsão

0.6666666666666666



> **Implementando Rede Neural**

Definição dos dados de treinamento

In [13]:
import numpy as np
import tensorflow as tf
from sklearn.metrics import accuracy_score

treino_x = np.array([porco1, porco2, porco3, cachorro1, cachorro2, cachorro3])  # dados (animais)
classificacoes_y = np.array([1, 1, 1, 0, 0, 0])  # 0 = cachorro, 1 = porco

Criação do modelo da rede neural

In [14]:
modelo = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu', input_shape=(3,)),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

modelo.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

Treinamento do modelo

In [15]:
modelo.fit(treino_x, classificacoes_y, epochs=100)

Epoch 1/100
1/1 [==============================] - 1s 678ms/step - loss: 0.6766 - accuracy: 0.5000
Epoch 2/100
1/1 [==============================] - 0s 11ms/step - loss: 0.6753 - accuracy: 0.5000
Epoch 3/100
1/1 [==============================] - 0s 19ms/step - loss: 0.6740 - accuracy: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 13ms/step - loss: 0.6728 - accuracy: 0.5000
Epoch 5/100
1/1 [==============================] - 0s 14ms/step - loss: 0.6715 - accuracy: 0.5000
Epoch 6/100
1/1 [==============================] - 0s 14ms/step - loss: 0.6702 - accuracy: 0.5000
Epoch 7/100
1/1 [==============================] - 0s 15ms/step - loss: 0.6689 - accuracy: 0.5000
Epoch 8/100
1/1 [==============================] - 0s 14ms/step - loss: 0.6677 - accuracy: 0.5000
Epoch 9/100
1/1 [==============================] - 0s 12ms/step - loss: 0.6664 - accuracy: 0.5000
Epoch 10/100
1/1 [==============================] - 0s 16ms/step - loss: 0.6652 - accuracy: 0.6667
Epoch 11/100
1/1 [

Previsão para um animal misterioso

In [16]:
animal_misterioso = np.array([[1, 1, 1]])
previsao = modelo.predict(animal_misterioso)
classe_prevista = round(previsao[0][0])  # Arredonda para a classe binária (0 ou 1)
print(classe_prevista)

1/1 [==============================] - 0s 58ms/step
0


Teste do modelo

In [17]:
misterio1 = np.array([[1, 1, 1]])
misterio2 = np.array([[1, 1, 0]])
misterio3 = np.array([[0, 1, 1]])

teste_x = np.array([misterio1, misterio2, misterio3])
teste_y = np.array([0, 1, 1])  # sei que o primeiro é um cachorro, e os outros dois são porcos

previsoes = modelo.predict(teste_x)
classes_previstas = np.round(previsoes).flatten()  # Arredonda para as classes binárias
print(classes_previstas)

1/1 [==============================] - 0s 77ms/step
[0. 1. 1.]


Avaliação da acurácia

In [18]:
taxa_acerto = accuracy_score(teste_y, classes_previstas)  # taxa de acerto da previsão
print(taxa_acerto)

1.0
